services:
  fastapi:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '6000:8000'
    volumes:
      - /root/nashith_practice/6.proj_with_db_bind_mount_poetry/mount_file_dir_1:/var/lib/test_1
      - /root/nashith_practice/6.proj_with_db_bind_mount_poetry/mount_file_dir_2:/var/lib/test_2
    restart: "no"
