services:
  fastapi:
    build:
      context: .
      target: builder
    container_name: validation-studio-fastapi-serivce
    env_file:
      - .env.broad
    ports:
      - '9000:8000'
    volumes:
    # The driver_path and data_transfrom_path should be absolute path starting from ValidartionStudioCloud)
      - /root/Docker_Full_Project/Project/${DRIVER_PATH}:/app/Project/${DRIVER_PATH}
      - /root/Docker_Full_Project/Project/${DATA_TRANSFORM_PATH}:/app/Project${DATA_TRANSFORM_PATH}

    restart: "no"
