services:
    db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Nashid007
    ports:
      - '27017:27017'
    container_name: mongoDB
    volumes:
      - mongodb_data:/data/db

  fastapi:
    build:
      context: .
      target: builder
    container_name: validation-studio-fastapi-serivce
    env_file:
      - .env.broad
    ports:
      - '9000:8000'
    volumes:
    # For bind mounting, the path should be absolute path
      - /root/Docker_Full_Project/Project/${DRIVER_PATH}:/app/Project/${DRIVER_PATH}
      - /root/Docker_Full_Project/Project/${DATA_TRANSFORM_PATH}:/app/Project${DATA_TRANSFORM_PATH}
    restart: "no"

volumes:
  mongodb_data:
